version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "cmake"
    directory: "/src"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - "dependencies"
      - "cmake"
